<a href="https://colab.research.google.com/github/ojaspaul123/Projects/blob/main/flight_price_analysis_and_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Load the dataset
file_path ='C:\\Users\\KIIT\\Desktop\\VS Code\\JNoteBook\\flight-price-analysis-and-prediction.csv'
df = pd.read_csv(file_path)
# Display the first few rows of the dataset
df.head()

,Airline,Source,Destination,Total_Stops,Price,Date,Month,Year,Dep_hours,Dep_min,Arrival_hours,Arrival_min,Duration_hours,Duration_min
0,IndiGo,Banglore,New Delhi,0,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,2,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,2,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,1,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,1,13302,1,3,2019,16,50,21,35,4,45

In [ ]:
%%markdown
Data Preprocessing

Data Preprocessing

In [ ]:
df.isnull().sum()

Airline           0
Source            0
Destination       0
Total_Stops       0
Price             0
Date              0
Month             0
Year              0
Dep_hours         0
Dep_min           0
Arrival_hours     0
Arrival_min       0
Duration_hours    0
Duration_min      0
dtype: int64

In [ ]:
df.describe()

,Total_Stops,Price,Date,Month,Year,Dep_hours,Dep_min,Arrival_hours,Arrival_min,Duration_hours,Duration_min
count,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.00000,67.000000
mean,1.000000,7704.746269,15.552239,5.432836,2019.552239,9.686567,21.343284,14.074627,30.298507,4.80597,26.865672
std,0.778499,3226.343602,8.464334,4.268361,0.501017,3.722206,16.823101,3.661071,16.419699,3.21096,13.309709
min,0.000000,2780.000000,1.000000,1.000000,2019.000000,5.000000,0.000000,1.000000,0.000000,1.00000,0.000000
25%,0.000000,4927.500000,8.500000,2.000000,2019.000000,7.000000,10.000000,13.000000,15.000000,2.00000,15.000000
50%,1.000000,7385.000000,16.000000,3.000000,2020.000000,9.000000,20.000000,15.000000,30.000000,4.00000,25.000000
75%,2.000000,10045.000000,22.000000,10.000000,2020.000000,11.000000,30.000000,16.000000,45.000000,8.00000,37.500000
max,2.000000,13882.000000,30.000000,12.000000,2020.000000,22.000000,50.000000,23.000000,55.000000,19.00000,50.000000